#!/usr/bin/env python3
import argparse
import os

import imgtestlib as testlib


def main():
    desc = "Build image for testing with boot-image"
    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument("distro", type=str, default=None, help="distro for the image to boot test")
    parser.add_argument("image_type", type=str, default=None, help="type of the image to boot test")
    parser.add_argument("config", type=str, help="config used to build the image")
    parser.add_argument("arch", default="", type=str, help="target arch of the image")

    args = parser.parse_args()
    distro = args.distro
    image_type = args.image_type
    config_path = args.config
    arch = os.uname().machine
    if args.arch:
        arch = args.arch

    testlib.build_image(distro, arch, image_type, config_path)


if __name__ == "__main__":
    main()
