#!/usr/bin/env python3
import argparse
import os
import subprocess as sp
import tempfile
import uuid
from contextlib import contextmanager


def get_rev_list(a, b):
    rev_list_bytes = sp.check_output(["git", "rev-list", f"{a}..{b}"])
    rev_list = rev_list_bytes.decode().splitlines()
    rev_list.reverse()
    return rev_list


@contextmanager
def setup_worktree():
    wd = os.path.abspath(".")
    branch_name = str(uuid.uuid4())
    with tempfile.TemporaryDirectory() as tmpdir:
        sp.check_output(["git", "worktree", "add", "-b", branch_name, f"{tmpdir}/repo"])
        yield tmpdir
        os.chdir(wd)
        # TODO: print errors
        sp.run(["git", "worktree", "remove", "--force", f"{tmpdir}/repo"], check=False)
        sp.run(["git", "branch", "-D", branch_name], check=False)


def gen_manifests(rev, workdir):
    sp.check_output(["git", "checkout", rev], cwd=f"{workdir}/repo")
    print(f"Generating manifests for {rev}")
    cmd = ["go", "run", "./cmd/gen-manifests",
           "--output", f"{workdir}/manifests/{rev}",
           "--commits=false", "--packages=false", "--containers=false", "--metadata=false",
           "--workers", "100"]
    # don't error out if this fails, some commits might not compile
    env = os.environ
    env["OSBUILD_TESTING_RNG_SEED"] = "2"
    ret = sp.run(cmd, cwd=f"{workdir}/repo", env=env, capture_output=True, check=False)
    if ret.returncode != 0:
        print(f"Manifest generation failed with exit code {ret.returncode}")
        print(ret.stderr)
        return None

    return rev


def diff_manifests(a, b, workdir):
    fname = f"{workdir}/manifests/{b}.diff"
    print(f"Generating {fname}", end=" ", flush=True)
    diff_proc = sp.run(["diff", "-r", f"{workdir}/manifests/{a}", f"{workdir}/manifests/{b}"],
                       capture_output=True, check=False)
    diff = diff_proc.stdout.decode()
    if diff:
        with open(fname, mode="w", encoding="utf-8") as diff_file:
            print("changes found")
            diff_file.write(diff)
            print(diff)
    else:
        print(f"No changes between {a} and {b}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("rev1")
    parser.add_argument("rev2")
    args = parser.parse_args()

    revs = get_rev_list(args.rev1, args.rev2)
    manifest_revs = []
    with setup_worktree() as workdir:
        for rev in revs:
            if manifest_rev := gen_manifests(rev, workdir):
                # collect the revs that successfully generated manifests in the order they were created
                manifest_revs.append(manifest_rev)
        for a, b in zip(manifest_revs[:-1], manifest_revs[1:]):
            diff_manifests(a, b, workdir)
        input()


if __name__ == "__main__":
    main()
